
// This copy of NeoFur for Unity is licensed to anthony.magdelaine@blackantmaster.com
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Draw.
        /// </summary>
        internal static string Foldout_DebugDraw {
            get {
                return ResourceManager.GetString("Foldout_DebugDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Detail Parameters.
        /// </summary>
        internal static string Foldout_LOD {
            get {
                return ResourceManager.GetString("Foldout_LOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fur Physics Parameters.
        /// </summary>
        internal static string Foldout_Physics {
            get {
                return ResourceManager.GetString("Foldout_Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        internal static string Foldout_Platforms {
            get {
                return ResourceManager.GetString("Foldout_Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessing.
        /// </summary>
        internal static string Foldout_Preprocess {
            get {
                return ResourceManager.GetString("Foldout_Preprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows.
        /// </summary>
        internal static string Foldout_Shadows {
            get {
                return ResourceManager.GetString("Foldout_Shadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Resistance Multiplier.
        /// </summary>
        internal static string Label_AirResistMult {
            get {
                return ResourceManager.GetString("Label_AirResistMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bend Exponent.
        /// </summary>
        internal static string Label_BendExp {
            get {
                return ResourceManager.GetString("Label_BendExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Point Dot Color.
        /// </summary>
        internal static string Label_ControlPointDotColor {
            get {
                return ResourceManager.GetString("Label_ControlPointDotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Point Dot Size.
        /// </summary>
        internal static string Label_ControlPointDotSize {
            get {
                return ResourceManager.GetString("Label_ControlPointDotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Point Ray Color.
        /// </summary>
        internal static string Label_ControlPointRayColor {
            get {
                return ResourceManager.GetString("Label_ControlPointRayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Debug Text.
        /// </summary>
        internal static string Label_DebugText {
            get {
                return ResourceManager.GetString("Label_DebugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mesh.
        /// </summary>
        internal static string Label_DisplayMesh {
            get {
                return ResourceManager.GetString("Label_DisplayMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Control Points.
        /// </summary>
        internal static string Label_DrawControlPoints {
            get {
                return ResourceManager.GetString("Label_DrawControlPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Fur Guides.
        /// </summary>
        internal static string Label_DrawFurGuides {
            get {
                return ResourceManager.GetString("Label_DrawFurGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fur Guide Gen Method.
        /// </summary>
        internal static string Label_FurGuideGenMethod {
            get {
                return ResourceManager.GetString("Label_FurGuideGenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Distance (cm).
        /// </summary>
        internal static string Label_FurLength {
            get {
                return ResourceManager.GetString("Label_FurLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fur Material.
        /// </summary>
        internal static string Label_FurMat {
            get {
                return ResourceManager.GetString("Label_FurMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity Influence.
        /// </summary>
        internal static string Label_GravityInfluence {
            get {
                return ResourceManager.GetString("Label_GravityInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Dot Color.
        /// </summary>
        internal static string Label_GuideDotColor {
            get {
                return ResourceManager.GetString("Label_GuideDotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Dot Size.
        /// </summary>
        internal static string Label_GuideDotSize {
            get {
                return ResourceManager.GetString("Label_GuideDotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Length.
        /// </summary>
        internal static string Label_GuideLength {
            get {
                return ResourceManager.GetString("Label_GuideLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Ray Color.
        /// </summary>
        internal static string Label_GuideRayColor {
            get {
                return ResourceManager.GetString("Label_GuideRayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD End Distance.
        /// </summary>
        internal static string Label_LODEndDist {
            get {
                return ResourceManager.GetString("Label_LODEndDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Distance from Camera.
        /// </summary>
        internal static string Label_LODMaxCamDist {
            get {
                return ResourceManager.GetString("Label_LODMaxCamDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD Minimum Shell Count.
        /// </summary>
        internal static string Label_LODMinShells {
            get {
                return ResourceManager.GetString("Label_LODMinShells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Compression Distance.
        /// </summary>
        internal static string Label_LODNearCompressionDist {
            get {
                return ResourceManager.GetString("Label_LODNearCompressionDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Compression Max.
        /// </summary>
        internal static string Label_LODNearCompressionMax {
            get {
                return ResourceManager.GetString("Label_LODNearCompressionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near Compression Min.
        /// </summary>
        internal static string Label_LODNearCompressionMin {
            get {
                return ResourceManager.GetString("Label_LODNearCompressionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD Start Distance.
        /// </summary>
        internal static string Label_LODStartDist {
            get {
                return ResourceManager.GetString("Label_LODStartDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Rotation from Normal.
        /// </summary>
        internal static string Label_MaxRotFromNormal {
            get {
                return ResourceManager.GetString("Label_MaxRotFromNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Stretch Distance Multiplier.
        /// </summary>
        internal static string Label_MaxStretchMult {
            get {
                return ResourceManager.GetString("Label_MaxStretchMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Stretch Distance Multiplier.
        /// </summary>
        internal static string Label_MinStretchMult {
            get {
                return ResourceManager.GetString("Label_MinStretchMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Direction Blend.
        /// </summary>
        internal static string Label_NormalDirectionBlend {
            get {
                return ResourceManager.GetString("Label_NormalDirectionBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Growth Mesh.
        /// </summary>
        internal static string Label_OverrideGrowthMesh {
            get {
                return ResourceManager.GetString("Label_OverrideGrowthMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Renderer.
        /// </summary>
        internal static string Label_OverrideRenderer {
            get {
                return ResourceManager.GetString("Label_OverrideRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Force Influence.
        /// </summary>
        internal static string Label_RadialInfluence {
            get {
                return ResourceManager.GetString("Label_RadialInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve Shadows.
        /// </summary>
        internal static string Label_RecieveShadows {
            get {
                return ResourceManager.GetString("Label_RecieveShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Camera.
        /// </summary>
        internal static string Label_SceneCamera {
            get {
                return ResourceManager.GetString("Label_SceneCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Casting Mode.
        /// </summary>
        internal static string Label_ShadowCastingMode {
            get {
                return ResourceManager.GetString("Label_ShadowCastingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Count.
        /// </summary>
        internal static string Label_ShellCount {
            get {
                return ResourceManager.GetString("Label_ShellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Fade.
        /// </summary>
        internal static string Label_ShellFade {
            get {
                return ResourceManager.GetString("Label_ShellFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Angle Stiffness.
        /// </summary>
        internal static string Label_SpringAngStiff {
            get {
                return ResourceManager.GetString("Label_SpringAngStiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Dampening Multiplier.
        /// </summary>
        internal static string Label_SpringDampMult {
            get {
                return ResourceManager.GetString("Label_SpringDampMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Length Stiffness.
        /// </summary>
        internal static string Label_SpringLenStiff {
            get {
                return ResourceManager.GetString("Label_SpringLenStiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Mesh Material ID.
        /// </summary>
        internal static string Label_SubMeshIndex {
            get {
                return ResourceManager.GetString("Label_SubMeshIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Compute Shader?.
        /// </summary>
        internal static string Label_UseComputeShader {
            get {
                return ResourceManager.GetString("Label_UseComputeShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Renderer Settings.
        /// </summary>
        internal static string Label_UseRendererSettings {
            get {
                return ResourceManager.GetString("Label_UseRendererSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Influence.
        /// </summary>
        internal static string Label_VelocityInfluence {
            get {
                return ResourceManager.GetString("Label_VelocityInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Influence.
        /// </summary>
        internal static string Label_WindInfluence {
            get {
                return ResourceManager.GetString("Label_WindInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional WindZone.
        /// </summary>
        internal static string Label_WindZone {
            get {
                return ResourceManager.GetString("Label_WindZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Resistance Multiplier.
        /// </summary>
        internal static string Tooltip_AirResistMult {
            get {
                return ResourceManager.GetString("Tooltip_AirResistMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the bendiness of fur strands.
        /// </summary>
        internal static string Tooltip_BendExp {
            get {
                return ResourceManager.GetString("Tooltip_BendExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Color of control point dots.
        /// </summary>
        internal static string Tooltip_ControlPointDotColor {
            get {
                return ResourceManager.GetString("Tooltip_ControlPointDotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Size of control point dots.
        /// </summary>
        internal static string Tooltip_ControlPointDotSize {
            get {
                return ResourceManager.GetString("Tooltip_ControlPointDotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Color of control point rays.
        /// </summary>
        internal static string Tooltip_ControlPointRayColor {
            get {
                return ResourceManager.GetString("Tooltip_ControlPointRayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display fur debug text when the game is running?.
        /// </summary>
        internal static string Tooltip_DebugText {
            get {
                return ResourceManager.GetString("Tooltip_DebugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fur attaches to the display mesh.
        /// </summary>
        internal static string Tooltip_DisplayMesh {
            get {
                return ResourceManager.GetString("Tooltip_DisplayMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Draw control points.
        /// </summary>
        internal static string Tooltip_DrawControlPoints {
            get {
                return ResourceManager.GetString("Tooltip_DrawControlPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Draw fur guides.
        /// </summary>
        internal static string Tooltip_DrawFurGuides {
            get {
                return ResourceManager.GetString("Tooltip_DrawFurGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates fur guides using the selected method (splines, morphs, normals). Spline or Morph modes depend on external spline data or morphs in the imported mesh.
        /// </summary>
        internal static string Tooltip_FurGuideGenMethod {
            get {
                return ResourceManager.GetString("Tooltip_FurGuideGenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum distance that fur shells can reach during growth.
        /// </summary>
        internal static string Tooltip_FurLength {
            get {
                return ResourceManager.GetString("Tooltip_FurLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A material which uses the NeoFur shader.
        /// </summary>
        internal static string Tooltip_FurMat {
            get {
                return ResourceManager.GetString("Tooltip_FurMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational influence on fur strands.
        /// </summary>
        internal static string Tooltip_GravityInfluence {
            get {
                return ResourceManager.GetString("Tooltip_GravityInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Color of fur guide dots.
        /// </summary>
        internal static string Tooltip_GuideDotColor {
            get {
                return ResourceManager.GetString("Tooltip_GuideDotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Size of fur guide dots.
        /// </summary>
        internal static string Tooltip_GuideDotSize {
            get {
                return ResourceManager.GetString("Tooltip_GuideDotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the guides generated from vertex normals.
        /// </summary>
        internal static string Tooltip_GuideLength {
            get {
                return ResourceManager.GetString("Tooltip_GuideLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug - Color of fur guide rays.
        /// </summary>
        internal static string Tooltip_GuideRayColor {
            get {
                return ResourceManager.GetString("Tooltip_GuideRayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from camera at which the number of fur shells will reach LOD Minimum.
        /// </summary>
        internal static string Tooltip_LODEndDist {
            get {
                return ResourceManager.GetString("Tooltip_LODEndDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from camera at which fur meshes (including LODs) are culled.
        /// </summary>
        internal static string Tooltip_LODMaxCamDist {
            get {
                return ResourceManager.GetString("Tooltip_LODMaxCamDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of fur shells remaining when the camera reaches LOD End Distance.
        /// </summary>
        internal static string Tooltip_LODMinShells {
            get {
                return ResourceManager.GetString("Tooltip_LODMinShells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance for LOD near compression effect.
        /// </summary>
        internal static string Tooltip_LODNearCompressionDist {
            get {
                return ResourceManager.GetString("Tooltip_LODNearCompressionDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tooltip_LODNearCompressionMax {
            get {
                return ResourceManager.GetString("Tooltip_LODNearCompressionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tooltip_LODNearCompressionMin {
            get {
                return ResourceManager.GetString("Tooltip_LODNearCompressionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from camera at which fur begins to transition between Shell Count and LOD Minimum.
        /// </summary>
        internal static string Tooltip_LODStartDist {
            get {
                return ResourceManager.GetString("Tooltip_LODStartDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum angle that fur strands can rotate from normals.
        /// </summary>
        internal static string Tooltip_MaxRotFromNormal {
            get {
                return ResourceManager.GetString("Tooltip_MaxRotFromNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier for the maximum distance fur can stretch. Should be greater than Min Stretch Distance Multiplier.
        /// </summary>
        internal static string Tooltip_MaxStretchMult {
            get {
                return ResourceManager.GetString("Tooltip_MaxStretchMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier for the minimum distance fur can stretch. Should be less than Max Stretch Distance Multiplier.
        /// </summary>
        internal static string Tooltip_MinStretchMult {
            get {
                return ResourceManager.GetString("Tooltip_MinStretchMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero to One value interpolating between mesh normal and physics control point for the position of the fur.
        /// </summary>
        internal static string Tooltip_NormalDirectionBlend {
            get {
                return ResourceManager.GetString("Tooltip_NormalDirectionBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A growth mesh to use instead of the mesh on the renderer. If using a SkinnedMeshRenderer this mesh must be rigged identically..
        /// </summary>
        internal static string Tooltip_OverrideGrowthMesh {
            get {
                return ResourceManager.GetString("Tooltip_OverrideGrowthMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is not set, the renderer on this gameobject will be used if one exist. Otherwise the one specified here will be used..
        /// </summary>
        internal static string ToolTip_OverrideRenderer {
            get {
                return ResourceManager.GetString("ToolTip_OverrideRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale for influence of radial force.
        /// </summary>
        internal static string Tooltip_RadialInfluence {
            get {
                return ResourceManager.GetString("Tooltip_RadialInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fur will recieve shadows.
        /// </summary>
        internal static string Tooltip_RecieveShadows {
            get {
                return ResourceManager.GetString("Tooltip_RecieveShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tooltip_SceneCamera {
            get {
                return ResourceManager.GetString("Tooltip_SceneCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How fur will cast shadows.
        /// </summary>
        internal static string Tooltip_ShadowCastingMode {
            get {
                return ResourceManager.GetString("Tooltip_ShadowCastingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of fur shells to grow.
        /// </summary>
        internal static string Tooltip_ShellCount {
            get {
                return ResourceManager.GetString("Tooltip_ShellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale for distance at which shells begin to fade.
        /// </summary>
        internal static string Tooltip_ShellFade {
            get {
                return ResourceManager.GetString("Tooltip_ShellFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular stiffness for fur strands.
        /// </summary>
        internal static string Tooltip_SpringAngStiff {
            get {
                return ResourceManager.GetString("Tooltip_SpringAngStiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale for dampening influence.
        /// </summary>
        internal static string Tooltip_SpringDampMult {
            get {
                return ResourceManager.GetString("Tooltip_SpringDampMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear stiffness for fur strands.
        /// </summary>
        internal static string Tooltip_SpringLenStiff {
            get {
                return ResourceManager.GetString("Tooltip_SpringLenStiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tooltip_SubMeshIndex {
            get {
                return ResourceManager.GetString("Tooltip_SubMeshIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tooltip_UseComputeShader {
            get {
                return ResourceManager.GetString("Tooltip_UseComputeShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy shadow settings from the renderer of the display mesh.
        /// </summary>
        internal static string Tooltip_UseRendererSettings {
            get {
                return ResourceManager.GetString("Tooltip_UseRendererSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale for influence of velocity .
        /// </summary>
        internal static string Tooltip_VelocityInfluence {
            get {
                return ResourceManager.GetString("Tooltip_VelocityInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale for influence of wind force.
        /// </summary>
        internal static string Tooltip_WindInfluence {
            get {
                return ResourceManager.GetString("Tooltip_WindInfluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Tooltip_WindZone {
            get {
                return ResourceManager.GetString("Tooltip_WindZone", resourceCulture);
            }
        }
    }
}
